[[module.imports]]
path = "github.com/hugomods/hugopress"

[[module.imports]]
path = "github.com/hbstack/blog"

[params.hugopress.modules.hb-docs.attributes.hb-main]
weight = 1

[params.hugopress.modules.hb-docs.hooks.head-begin]

[params.hugopress.modules.hb-docs.hooks.hb-header-nav-begin]

[params.hb.docs]
date_format = ":date_long"
